export * from './base.mapper';
export * from './s3.mapper';
export * from './image.mapper';
export * from './tag.mapper';
export * from './gallery.mapper';
export * from './cloudfront.mapper';
export * from './resourcegrouptaggingapi.mapper';
export * from './event.mapper';
export * from './mail.mapper';
export * from './user.mapper';
export * from "./access.mapper"