---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Express KOFC9544 API powered by API Gateway and Lambda
Parameters:
    ParentDomainName:
        Type: String
        Description: API Domain name
        Default: "kofc9544.ca"
    DomainName:
        Type: String
        Description: API Domain name
        Default: $DomainName
    Certificate:
        Type: String
        Description: Certificate
        Default: $Certificate
    BucketNameImages:
        Type: String
        Description: Bucket for Images
        Default: $BucketNameImages
    Stage:
        Type: String
        Description: Bucket for Images
        Default: $Stage
    DbHost:
        Type: String
        Description: Bucket for Images
        Default: $DbHost
    DbName:
        Type: String
        Description: Bucket for Images
        Default: $DbName
    DbUserName:
        Type: String
        Description: Bucket for Images
        Default: $DbUserName
    DbPassword:
        Type: String
        Description: Bucket for Images
        Default: $DbPassword
    NodeEnv:
        Type: String
        Description: Bucket for Images
        Default: $NodeEnv

    TokenSecret:
        Type: String
        Description: Token Secret
        Default: $TokenSecret
    CacheId:
        Type: String
        Description: Cache ID
        Default: $CacheId

    RDSHost:
        Type: String
        Description: RDS Host URL
        Default: $RDSHost

    RDSDBName:
        Type: String
        Description: RDS Database
        Default: $RDSDBName

    DEBUG:
        Type: String
        Description: Cache ID
        Default: sequelize:sql*


Conditions:
    UseDomainName: !Not
        - !Equals
            - !Ref DomainName
            - ''
    UseCertificate: !Not
        - !Equals
            - !Ref Certificate
            - ''
Resources:
    ExpressApi:
        Type: AWS::Serverless::Api
        Properties:
            StageName: !Ref Stage
            BinaryMediaTypes:
                - image/png
                - image/jpg
                - image/jpeg
                - multipart/form-data

    ExpressLambdaFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: ./dist
            PackageType: Zip
            Runtime: nodejs20.x
            Handler: lambda.handler
            Environment:
                Variables:
                    DB_NAME: !Ref DbName
                    STAGE: !Ref Stage
                    DB_HOST: !Ref DbHost
                    DB_USERNAME: !Ref DbUserName
                    DB_PASSWORD: !Ref DbPassword
                    NODE_ENV: !Ref NodeEnv
                    TOKEN_SECRET: !Ref TokenSecret
                    DEBUG: !Ref DEBUG
                    RDS_HOST: !Ref RDSHost
                    RDS_DB: !Ref RDSDBName
            MemorySize: 2048
            Timeout: 900
            Events:
                ApiEvent:
                    Type: Api
                    Properties:
                        Path: /{proxy+}
                        Method: ANY
                        RestApiId: !Ref ExpressApi
            Policies:
                - SESBulkTemplatedCrudPolicy_v2:
                      IdentityName: kofc9544.ca
                      TemplateName: DefaultEmailTemplate
                - SESEmailTemplateCrudPolicy: {}
                - S3WritePolicy:
                      BucketName: !Ref BucketNameImages
                - Version: '2012-10-17'
                  Statement:
                      - Effect: Allow
                        Action:
                            - tag:GetResources
                            - cloudfront:CreateInvalidation
                        Resource: '*'