Resources:
    ExpressApi:
        Type: AWS::Serverless::Api
        Properties:
            StageName: !Ref Stage
            BinaryMediaTypes:
                - image/png
                - image/jpg
                - image/jpeg
                - multipart/form-data

    ExpressLambdaFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: ./dist
            PackageType: Zip
            Runtime: nodejs20.x
            Handler: lambda.handler
            Environment:
                Variables:
                    DB_NAME: !Ref DbName
                    STAGE: !Ref Stage
                    DB_HOST: !Ref DbHost
                    DB_USERNAME: !Ref DbUserName
                    DB_PASSWORD: !Ref DbPassword
                    NODE_ENV: !Ref NodeEnv
                    TOKEN_SECRET: !Ref TokenSecret
                    DEBUG: !Ref DEBUG
                    RDS_HOST: !Ref RDSHost
                    RDS_DB: !Ref RDSDBName
            MemorySize: 2048
            Timeout: 900
            Events:
                ApiEvent:
                    Type: Api
                    Properties:
                        Path: /{proxy+}
                        Method: ANY
                        RestApiId: !Ref ExpressApi
            Policies:
                - SESBulkTemplatedCrudPolicy_v2:
                      IdentityName: kofc9544.ca
                      TemplateName: DefaultEmailTemplate
                - SESEmailTemplateCrudPolicy: {}
                - S3WritePolicy:
                      BucketName: !Ref BucketNameImages
                - Version: '2012-10-17'
                  Statement:
                      - Effect: Allow
                        Action:
                            - tag:GetResources
                            - cloudfront:CreateInvalidation
                        Resource: '*'